### ISSUE TITLE
about DANtesting.py problem 

### ISSUE THREAD

**Issue by qmj123** [MarekKowalski/DeepAlignmentNetwork#45]
Hi,When I run CameraDemo.py,there has a problem that
 F:\code\DeepAlignmentNetwork-master\DeepAlignmentNetwork> python .\DANtesting.py
Loading network...
Input shape: (None, 1, 112, 112)
Network being tested: ..\DAN.npz
Normalization is set to: corners
Failure threshold is set to: 0.08
Processing common subset of the 300W public test set (test sets of LFPW and HELEN)
E:\anaconda\lib\site-packages\numpy\core\fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
Average error: nan
Processing challenging subset of the 300W public test set (IBUG dataset)
Average error: nan
Showing results for the entire 300W pulic test set (IBUG dataset, test sets of LFPW and HELEN
Average error: nan
Traceback (most recent call last):
  File ".\DANtesting.py", line 35, in <module>
    tests.AUCError(fullsetErrs, failureThreshold, showCurve=showCED)
  File "F:\code\DeepAlignmentNetwork-master\DeepAlignmentNetwork\tests.py", line 52, in AUCError
    ced =  [float(np.count_nonzero([errors <= x])) / nErrors for x in xAxis]
  File "F:\code\DeepAlignmentNetwork-master\DeepAlignmentNetwork\tests.py", line 52, in <listcomp>
    ced =  [float(np.count_nonzero([errors <= x])) / nErrors for x in xAxis]
ZeroDivisionError: float division by zero
What is the reason? Can you help me ?
Thank you !

**Comment by MarekKowalski** [comment]
Hi,

It sounds like the datasets were not generated correctly, division by 0 suggests that there are no images in the dataset.
Did you download the images from the ibug website and extract them to the correct directory as described in the readme?

Marek

**Comment by qmj123** [comment]
Ok！Too stupid!  Thank you ! Thank you !

**Comment by qmj123** [comment]
I download these dataset but have problem that
![image](https://user-images.githubusercontent.com/33482101/49586643-a8fa7200-f99c-11e8-83f2-36ae13082078.png)

**Comment by MarekKowalski** [comment]
Have you tried debugging this? Does a key like that exist in the dictionary? Do the file extensions match?

Marek

**Comment by qmj123** [comment]
ok! Thanks!

**Comment by Tomhouxin** [comment]
hi, when I run CameraDemp.py, get Error:
Loading network...
Input shape: (None, 1, 112, 112)
ERROR (theano.gof.opt): Optimization failure due to: local_abstractconv_check
ERROR (theano.gof.opt): node: AbstractConv2d{convdim=2, border_mode='half', subsample=(1, 1), filter_flip=True, imshp=(None, 1, 112, 112), kshp=(64, 1, 3, 3), filter_dilation=(1, 1), num_groups=1, unshared=False}(inputs, W)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):

**Comment by Tomhouxin** [comment]
hi, when I run CameraDemp.py, get Error:
Loading network...
Input shape: (None, 1, 112, 112)
ERROR (theano.gof.opt): Optimization failure due to: local_abstractconv_check
ERROR (theano.gof.opt): node: AbstractConv2d{convdim=2, border_mode='half', subsample=(1, 1), filter_flip=True, imshp=(None, 1, 112, 112), kshp=(64, 1, 3, 3), filter_dilation=(1, 1), num_groups=1, unshared=False}(inputs, W)
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):

**Comment by MarekKowalski** [comment]
Hey,

This looks like a theano issue to me. Do you use the version I specified in the readme?
Have you tried searching theano-related GitHub issues?
Also, what is in the traceback?

Thanks,

Marek

**Comment by Tomhouxin** [comment]
yes, I use :
![image](https://user-images.githubusercontent.com/23637856/59573228-8338ed00-90e4-11e9-833c-40657670ea62.png)

**Comment by MarekKowalski** [comment]
Hi,
Did you try running some other theano examples to determine whether the issue is in the DAN code (this repo) or with your Theano installation in general?

Thanks,

Marek
