### ISSUE TITLE
cannot run ImageDemo.py

### ISSUE THREAD

**Issue by ahpu2014** [MarekKowalski/DeepAlignmentNetwork#59]
Hi,
when I run ImageDemo.py ,some mistakes always happen.
eg:ValueError: mismatch: parameter has shape (256, 2) but value to set has shape (256, 3136)
Thanks for your reply!

**Comment by MarekKowalski** [comment]
Can you give more context, for example the full text of the exception with trace and line number?

Thanks,

Marek

**Comment by Itajobi** [comment]
HI,
How do I run imageDemo.py without encountering error.
The error message is;
Traceback (most recent call last):
File "C:\Users\xpert\Desktop\Data Analysis\Python Programming\Coding Files\C8Ex8 - ImageDemo.py", line 42, in <module>
    imageDemo()  # Create GUI
    ^^^^^^^^^^^
File "C:\Users\xpert\Desktop\Data Analysis\Python Programming\Coding Files\C8Ex8 - ImageDemo.py", line 10, in __init__
    caImage = PhotoImage(file="image/ca.gif")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

 File "C:\Program Files\Python311\Lib\tkinter\__init__.py", line 4130, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)

 File "C:\Program Files\Python311\Lib\tkinter\__init__.py", line 4075, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't recognize data in image file "image/ca.gif"
